- name: install centos/redhat dependencies
  yum:
    name:
      - python36-pip
      - python36-devel
      - python36-pyOpenSSL #required for ansible pip installation
      - git
      - gcc
    enablerepo: epel
    state: present
  when: ansible_os_family == 'RedHat'

- name: install debian/ubuntu dependencies
  apt:
    name:
      - python3-pip
      - git
      - gcc
    state: present
  when: ansible_os_family == 'Debian'

- name: Install ansible and docker python module
  pip:
    name:
      - docker
      - ansible
    state: present 
    executable: pip3

- name: Clone AWX 
  git:
    repo: "{{ awx_repo }}"
    dest: "{{ awx_repo_dir }}"
    version: "{{ awx_version }}"
    accept_hostkey: yes

- name: Setup awx config file
  template:
    src: inventory.j2
    dest: "{{ awx_repo_dir }}/installer/inventory"

- name: AWX ansible installation
  command: "ansible-playbook -i inventory install.yml"
  args:
    chdir: "{{ awx_repo_dir }}/installer"
    creates: /etc/awx_playbook_complete

- name: Create a file to mark whether this playbook has completed.
  file:
    path: /etc/awx_playbook_complete
    state: touch
  changed_when: False

